version: '2'

services:
    nginx:
        image: nginx:stable-alpine
        container_name: jocop_nginx
        ports:
            - "80:80"
        volumes:
            - ./code:/var/www/html/code
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - frontend-network
            - backend-network

    mysql:
        image: mysql:8.0.18 
        container_name: jocop_mysql 
        ports:
            - "13306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=JO281308
            - MYSQL_USER=jocop
            - MYSQL_PASSWORD=JO281308
        networks:
            - backend-network

    php:
        image: php:7.4-fpm
        container_name: jocop_php
        volumes:
            - ./code:/var/www/html/code
        ports:
            - "9000:9000"
        networks:
            - backend-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: jocop_phpmyadmin 
        ports:
            - "18183:80"
        environment:
            PMA_HOST: mysql
            PMA_USER: jocop
            PMA_PASSWORD: JO281308
        depends_on:
            - mysql
        networks:
            - backend-network

networks:
    frontend-network:
    backend-network:



